### ISSUE TITLE
Path rendered with fill despite having none

### ISSUE THREAD

**Issue by ygra** [fskpf/svg2roughjs#68] opened 2021-07-17 15:34 UTC
Can be seen with https://commons.wikimedia.org/wiki/File:Clock_group.svg

The path that renders the 3/6/9/12 hour ticks is drawn with a fill which isn't how it appears in the original image:

![image](https://user-images.githubusercontent.com/1692688/126042041-f2959c11-4a00-4db4-b1d3-60f6946b2945.png)

Original:

![image](https://user-images.githubusercontent.com/1692688/126042051-7dcfc565-6e5d-4de1-b0b0-89e53c92f98e.png)

**Comment by ygra** [comment] 2021-07-17 15:51
The path itself is just two lines (`M ... L ... M ... L ...`), but inside a symbol that's instantiated with a `use`. Perhaps that changes how it's rendered. It shouldn't have any area to fill, though, even though the path itself has an unset fill and thus should appear black.

Perhaps an issue with rough.js instead of our code, though. Could be circumvented by drawing two separate paths split on the move command in the middle.

**Comment by fskpf** [comment] 2021-07-17 22:15
This is the same issue as #71. Disabling `combineNestedSvgPaths` would also resolve the attached SVG here. Therefore I'll close this issue as duplicate of #71.

**Closed by fskpf** 2021-07-17 22:15 UTC
